package report

import (
	"fmt"
	"io"
	"text/template"
)

const markdownTemplate = `# Network Analysis Report

**Generated:** {{ .GeneratedAt.Format "2006-01-02 15:04:05" }}
**File:** {{ .PcapPath }}

---

## Overview

| Metric | Value |
|--------|-------|
| Total Packets | {{ .Overview.TotalPackets }} |
| Total Bytes | {{ formatBytes .Overview.TotalBytes }} |
| Duration | {{ .Overview.Duration }} |
| Packets/sec | {{ printf "%.2f" .Overview.PacketsPerSec }} |
| Bytes/sec | {{ formatBytes (int64 .Overview.BytesPerSec) }} |
| Total Flows | {{ .Overview.TotalFlows }} |

---

## Protocol Distribution

| Protocol | Packets | Bytes | % |
|----------|---------|-------|---|
{{- range .ProtocolStats }}
| {{ .Protocol }} | {{ .Packets }} | {{ formatBytes .Bytes }} | {{ printf "%.1f%%" .Percent }} |
{{- end }}

---

## Top Flows by Bytes

| Flow | Source | Destination | Protocol | Packets | Bytes | Duration | SNI |
|------|--------|-------------|----------|---------|-------|----------|-----|
{{- range .TopFlowsByBytes }}
| {{ .ID }} | {{ .SrcIP }}:{{ .SrcPort }} | {{ .DstIP }}:{{ .DstPort }} | {{ .Protocol }} | {{ .Packets }} | {{ .BytesStr }} | {{ .Duration }} | {{ .SNI }} |
{{- end }}

---

## Top Talkers

| IP Address | Packets | Bytes | Flows |
|------------|---------|-------|-------|
{{- range .TopTalkers }}
| {{ .IP }} | {{ .Packets }} | {{ formatBytes .Bytes }} | {{ .Flows }} |
{{- end }}

---

## Expert Events Summary

| Severity | Count |
|----------|-------|
| Error | {{ index .EventSummary.BySeverity "error" }} |
| Warning | {{ index .EventSummary.BySeverity "warning" }} |
| Note | {{ index .EventSummary.BySeverity "note" }} |

{{- if .TopEvents }}

### Top Events

| Severity | Group | Type | Message | Packets |
|----------|-------|------|---------|---------|
{{- range .TopEvents }}
| {{ .Severity }} | {{ .Group }} | {{ .Type }} | {{ .Message }} | {{ .Packets }} |
{{- end }}
{{- end }}

---

*Report generated by pktanalyzer*
`

// WriteMarkdown writes the report in Markdown format.
func WriteMarkdown(w io.Writer, data *Data) error {
	funcMap := template.FuncMap{
		"formatBytes": FormatBytes,
		"int64":       func(f float64) int64 { return int64(f) },
	}

	t, err := template.New("report").Funcs(funcMap).Parse(markdownTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	return t.Execute(w, data)
}
